. "$HOME/.cargo/env"

export REMOTE_HOST=khang@100.116.207.128
export BRAIN_USER=khang

export OPENCODE_EXPERIMENTAL_MARKDOWN=true
export OPENCODE_EXPERIMENTAL_PLAN_MODE=false
export OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT=false
export OPENCODE_EXPERIMENTAL=true

export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
export CLAUDE_CODE_NO_FLICKER=1
